apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: kumarsumeet/book-catalog:latest
        ports:
        - containerPort: 80
        env:
        - name: DATABASE_URL
          value: "postgresql://sumeet_sit722_part2_user:0tdcA4nfgvkt3qQumlNorLRlGFF9Fkc6@dpg-cr8numq3esus73b9nq4g-a.oregon-postgres.render.com/sumeet_sit722_part2"
---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: NodePort
  selector:
    app: book-catalog
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30007
